apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: retail-mesh
spec:
  selector:
    matchLabels: {app: notification-service}
  template:
    metadata:
      labels: {app: notification-service}
    spec:
      containers:
      - name: notification-service
        image: awezkhan6899/retail-notification:latest
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: retail-mesh
spec:
  ports: [{port: 5003}]
  selector: {app: notification-service}
